# GENERATE DATA FRAME WITH ONE ROW PER NVI-package ----
NVIpackages <- as.data.frame(rbind(c("NVIconfig",
                                     "Private",
                                     "Configuration information necessary for some NVIverse functions"),
                                   c("NVIdb",
                                     "Public",
                                     "Tools to facilitate the use of NVI's databases"),
                                   c("NVIdata",
                                     "Public",
                                     "Provides basic data for use in NVIverse"),
                                   c("NVImap",
                                     "Public",
                                     "Tools to facilitate handling spatial objects at NVI"),
                                   c("NVIpretty",
                                     "Public",
                                     "Tools to make R-output pretty in accord with NVI's graphical profile"),
                                   c("NVIbatch",
                                     "Public",
                                     "Tools to facilitate the running of R-scripts in batch mode at NVI"),
                                   c("OKplan",
                                     "Public",
                                     "Tools to facilitate the planning of surveillance programmes for the NFSA"),
                                   c("OKcheck",
                                     "Public",
                                     "Tools to facilitate checking of data from national surveillance programmes"),
                                   c("NVIcheckmate",
                                     "Public",
                                     "Extension of checkmate with argument checking adapted for NVIverse"),
                                   c("NVIpackager",
                                     "Public",
                                     "Tools to facilitate the development of NVIverse packages")))
colnames(NVIpackages) <- c("Package", "Status", "Description")

# SAVE IN PACKAGE DATA ----
usethis::use_data(name = NVIpackages, overwrite = TRUE, internal = FALSE)
